version: '3'

networks:
  ignite-interproject-network:
    external:
      name: ignite-interproject-network

services:
  postgres:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5433
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5433:5432'
    restart: unless-stopped
  ignite-cross-chain-bridge:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - 0.0.0.0:${DOCKER_COMPOSE_PORT}:80
    networks:
      default: null
      ignite-interproject-network:
        aliases:
          - ignite-cross-chain-bridge
    volumes:
      - /data/ignite-cross-chain-bridge-backend/logs:/usr/src/app/logs
