version: '3'

networks:
  ignite-interproject-network:
    external:
      name: ignite-interproject-network
      
services:
  ignite-cross-chain-bridge:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - 0.0.0.0:${DOCKER_COMPOSE_PORT}:80
    networks:
      default: null
      ignite-interproject-network: null
        aliases:
          - ignite-cross-chain-bridge
    volumes:
      - /data/ignite-cross-chain-bridge-backend/logs:/usr/src/app/logs
